### PR TITLE
bug/102_bad-extends-documents-decorators-for-app-roles

### LINKED ISSUE #102: The method PersistedRole.addAgent(agentPointer) doesn't work properly
When trying to add an agent into a role document using the PersistedRole.addAgent() method, it throws the following error: `IllegalStateError: The context of the current role, does not support roles management.`

The next property from the role object might be useful for fixing the issue: `_roles : null`

### PR DESCRIPTION
**Pull request by roddolf**
- Fixed #102 - Move the addition of the factory decorator for perissted app roles to the app context

### CODE REVIEW

File: src/Documents.ts [hunk 1]
```diff
@@ -32,8 +32,8 @@ export class Class implements Pointer.Library, Pointer.Validator, ObjectSchema.R
 	private _jsonldConverter:JSONLD.Converter.Class;
 	get jsonldConverter():JSONLD.Converter.Class { return this._jsonldConverter; }
 
-	private _documentDecorators:Map<string, {decorator:Function, parameters?:any[]}>;
-	get documentDecorators():Map<string, {decorator:Function, parameters?:any[]}> { return this._documentDecorators; }
+	private _documentDecorators:Map<string, {decorator:( object:Object, ...parameters:any[] ) => Object, parameters?:any[]}>;
```
Comment (MiguelAraCo) [inline src/Documents.ts]: You are using the type `{decorator:( object:Object , ...parameters:any[] ) => Object, parameters?:any[]  }` everywhere. Please create a type for it to improve the readability.
