### PR TITLE
bug/114_problem-with-uris-relative-to-another

### LINKED ISSUE #114: Creating an Agent not recognizing relative id's
When trying to persist a new agent, an IllegalArgumentError is being thrown by Documents.persistDocument function.
The following code can be used to reproduce it.
```typescript
let newAgent:Agent.Class = Agent.Factory.create( "New Agent Name", "new-agent@mail.com", "password" );
newAgent.id = "new-agent-name/";
let agents:Agents.Class = appContext.auth.agents;
agents.register( agent, "agent-slug" );
```
screen shot 2016-11-28 at 10 07 22 am

But when commenting the id the function is being called successfully.
```typescript
let newAgent:Agent.Class = Agent.Factory.create( "New Agent Name", "new-agent@mail.com", "password" );
// newAgent.id = "new-agent-name/";
let agents:Agents.Class = appContext.auth.agents;
agents.register( agent, "agent-slug" );
```

### LINKED ISSUE #115: Document being persisted error when persisting after a platform error
When trying to persist a **new** document (in this case an Agent) after the first persist of the document fails throwing a platform error, in this case a `409 - Conflict - The URI is already in use error`, the SDK throws an error stating:
```
The document is already being persisted.
IllegalArgumentError at Documents.persistDocument (http://localhost:8000/jspm_packages/npm/carbonldp@0.39.0/Documents.js:606:35) at Documents.createChild (http://localhost:8000/jspm_packages/npm/carbonldp@0.39.0/Documents.js:169:21) at eval 
```

This could be caused due to a `document being persisted flag` not being reset on method `persistDocument` of `Documents.ts` class when a platform errors occurs.

### LINKED ISSUE #118: Product description on NPM page is missing a space in the brand name
Minor thing...
"JavaScript/TypeScript SDK to create CarbonLDP's Applications"
Should be:
"JavaScript/TypeScript SDK to create Carbon LDP applications"

### PR DESCRIPTION
**Pull request by roddolf**
- Fixed #114 - Error asking if URI is relative to another one
- Fixed #115 - Error when retrying to persist an object after the server sent an error
- Fixed #118 - Incorrect product brand name

### CODE REVIEW

File: src/Documents.ts [hunk 1]
```diff
@@ -776,6 +776,9 @@ export class Class implements Pointer.Library, Pointer.Validator, ObjectSchema.R
 				persistedProtectedDocument,
 				response,
 			];
+		}, ( error ) => {
```
Comment (MiguelAraCo) [inline src/Documents.ts]: To improve readability please use a catch statement instead of sending the error function as a second parameter.

File: src/Documents.ts [hunk 2]
```diff
@@ -776,6 +776,9 @@ export class Class implements Pointer.Library, Pointer.Validator, ObjectSchema.R
...
+			delete document[ "__CarbonSDK_InProgressOfPersisting" ];
+			throw error;
```
Comment (MiguelAraCo) [inline src/Documents.ts]: Even though a throw statement works, we should try to avoid using it inside functions that return a promise. Please use `return Promise.reject( error );` whenever you want to throw an error.
